workflows:
  android_debug_build:
    name: Build Android Debug APK
    instance_type: mac_mini
    environment:
      node: 16.20.0
      java: 11
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android debug APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
